#!/bin/sh

./files
./flashcards
echo -n "Input your user, the one as said in /home/<yourusernamehere>"
read Auser
chown -R $Auser:$Auser ~/.sets/fcards-python
chown -R $Auser:$Auser ~/.sets/VERSION
chmod -R =rwx ~/.sets/fcards-python
chmod -R =rwx ~/.sets/VERSION
